# Run both providers (Python + Node). "..." keeps any auto-detected providers.
providers = ['...', 'python']

[phases.install]
# Install frontend deps in its folder (adjust path as needed)
cmds = [
  "cd frontend && npm ci"
]
# Make node binaries available (e.g., vite/tsc)
paths = ["/app/frontend/node_modules/.bin"]

[phases.build]
# Build the frontend
cmds = [
  "cd frontend && npm run build"
]

[start]
# Start your Python app
cmd = "cd backend && python app.py"
